# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff7abb71ff03d366ce79ec78260a9c2032cf80fa5cd1cc47dee6dc2f94512faeae874b3c8e3c3e60fd128f35a2b4992013803a62d061c91fa1690bd0c8d91ab5

test:
  secret_key_base: 984d8f2d11031279a94ffc9148a7f2497a07778296412dba9e12fba4d7822a393db1a25dc9119be351656c71da9adc8d8b8ed593c2d6f1498c44df12da07db8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
